#!/bin/sh
## postinstall

# Add Orbit Desktop Channel to Fleet agent plist
/usr/bin/plutil -insert EnvironmentVariables.ORBIT_DESKTOP_CHANNEL -string "stable" /Library/LaunchDaemons/com.fleetdm.orbit.plist

# Enable Fleet Destop via Fleet agent plist
/usr/bin/plutil -insert EnvironmentVariables.ORBIT_FLEET_DESKTOP -string "true" /Library/LaunchDaemons/com.fleetdm.orbit.plist

# Start the Fleet agent
/bin/launchctl load /Library/LaunchDaemons/com.fleetdm.orbit.plist  

exit 0		## Success
exit 1		## Failure
